// Code generated by protoc-gen-go. DO NOT EDIT.
// source: signalling.proto

package tdproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type KeyType int32

const (
	KeyType_AES_GCM_128 KeyType = 90
	KeyType_AES_GCM_256 KeyType = 91
)

var KeyType_name = map[int32]string{
	90: "AES_GCM_128",
	91: "AES_GCM_256",
}

var KeyType_value = map[string]int32{
	"AES_GCM_128": 90,
	"AES_GCM_256": 91,
}

func (x KeyType) Enum() *KeyType {
	p := new(KeyType)
	*p = x
	return p
}

func (x KeyType) String() string {
	return proto.EnumName(KeyType_name, int32(x))
}

func (x *KeyType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(KeyType_value, data, "KeyType")
	if err != nil {
		return err
	}
	*x = KeyType(value)
	return nil
}

func (KeyType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_39f66308029891ad, []int{0}
}

// State transitions of the client
type C2S_Transition int32

const (
	C2S_Transition_C2S_NO_CHANGE                C2S_Transition = 0
	C2S_Transition_C2S_SESSION_INIT             C2S_Transition = 1
	C2S_Transition_C2S_SESSION_COVERT_INIT      C2S_Transition = 11
	C2S_Transition_C2S_EXPECT_RECONNECT         C2S_Transition = 2
	C2S_Transition_C2S_SESSION_CLOSE            C2S_Transition = 3
	C2S_Transition_C2S_YIELD_UPLOAD             C2S_Transition = 4
	C2S_Transition_C2S_ACQUIRE_UPLOAD           C2S_Transition = 5
	C2S_Transition_C2S_EXPECT_UPLOADONLY_RECONN C2S_Transition = 6
	C2S_Transition_C2S_ERROR                    C2S_Transition = 255
)

var C2S_Transition_name = map[int32]string{
	0:   "C2S_NO_CHANGE",
	1:   "C2S_SESSION_INIT",
	11:  "C2S_SESSION_COVERT_INIT",
	2:   "C2S_EXPECT_RECONNECT",
	3:   "C2S_SESSION_CLOSE",
	4:   "C2S_YIELD_UPLOAD",
	5:   "C2S_ACQUIRE_UPLOAD",
	6:   "C2S_EXPECT_UPLOADONLY_RECONN",
	255: "C2S_ERROR",
}

var C2S_Transition_value = map[string]int32{
	"C2S_NO_CHANGE":                0,
	"C2S_SESSION_INIT":             1,
	"C2S_SESSION_COVERT_INIT":      11,
	"C2S_EXPECT_RECONNECT":         2,
	"C2S_SESSION_CLOSE":            3,
	"C2S_YIELD_UPLOAD":             4,
	"C2S_ACQUIRE_UPLOAD":           5,
	"C2S_EXPECT_UPLOADONLY_RECONN": 6,
	"C2S_ERROR":                    255,
}

func (x C2S_Transition) Enum() *C2S_Transition {
	p := new(C2S_Transition)
	*p = x
	return p
}

func (x C2S_Transition) String() string {
	return proto.EnumName(C2S_Transition_name, int32(x))
}

func (x *C2S_Transition) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(C2S_Transition_value, data, "C2S_Transition")
	if err != nil {
		return err
	}
	*x = C2S_Transition(value)
	return nil
}

func (C2S_Transition) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_39f66308029891ad, []int{1}
}

// State transitions of the server
type S2C_Transition int32

const (
	S2C_Transition_S2C_NO_CHANGE           S2C_Transition = 0
	S2C_Transition_S2C_SESSION_INIT        S2C_Transition = 1
	S2C_Transition_S2C_SESSION_COVERT_INIT S2C_Transition = 11
	S2C_Transition_S2C_CONFIRM_RECONNECT   S2C_Transition = 2
	S2C_Transition_S2C_SESSION_CLOSE       S2C_Transition = 3
	// TODO should probably also allow EXPECT_RECONNECT here, for DittoTap
	S2C_Transition_S2C_ERROR S2C_Transition = 255
)

var S2C_Transition_name = map[int32]string{
	0:   "S2C_NO_CHANGE",
	1:   "S2C_SESSION_INIT",
	11:  "S2C_SESSION_COVERT_INIT",
	2:   "S2C_CONFIRM_RECONNECT",
	3:   "S2C_SESSION_CLOSE",
	255: "S2C_ERROR",
}

var S2C_Transition_value = map[string]int32{
	"S2C_NO_CHANGE":           0,
	"S2C_SESSION_INIT":        1,
	"S2C_SESSION_COVERT_INIT": 11,
	"S2C_CONFIRM_RECONNECT":   2,
	"S2C_SESSION_CLOSE":       3,
	"S2C_ERROR":               255,
}

func (x S2C_Transition) Enum() *S2C_Transition {
	p := new(S2C_Transition)
	*p = x
	return p
}

func (x S2C_Transition) String() string {
	return proto.EnumName(S2C_Transition_name, int32(x))
}

func (x *S2C_Transition) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(S2C_Transition_value, data, "S2C_Transition")
	if err != nil {
		return err
	}
	*x = S2C_Transition(value)
	return nil
}

func (S2C_Transition) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_39f66308029891ad, []int{2}
}

// Should accompany all S2C_ERROR messages.
type ErrorReasonS2C int32

const (
	ErrorReasonS2C_NO_ERROR         ErrorReasonS2C = 0
	ErrorReasonS2C_COVERT_STREAM    ErrorReasonS2C = 1
	ErrorReasonS2C_CLIENT_REPORTED  ErrorReasonS2C = 2
	ErrorReasonS2C_CLIENT_PROTOCOL  ErrorReasonS2C = 3
	ErrorReasonS2C_STATION_INTERNAL ErrorReasonS2C = 4
	ErrorReasonS2C_DECOY_OVERLOAD   ErrorReasonS2C = 5
	ErrorReasonS2C_CLIENT_STREAM    ErrorReasonS2C = 100
	ErrorReasonS2C_CLIENT_TIMEOUT   ErrorReasonS2C = 101
)

var ErrorReasonS2C_name = map[int32]string{
	0:   "NO_ERROR",
	1:   "COVERT_STREAM",
	2:   "CLIENT_REPORTED",
	3:   "CLIENT_PROTOCOL",
	4:   "STATION_INTERNAL",
	5:   "DECOY_OVERLOAD",
	100: "CLIENT_STREAM",
	101: "CLIENT_TIMEOUT",
}

var ErrorReasonS2C_value = map[string]int32{
	"NO_ERROR":         0,
	"COVERT_STREAM":    1,
	"CLIENT_REPORTED":  2,
	"CLIENT_PROTOCOL":  3,
	"STATION_INTERNAL": 4,
	"DECOY_OVERLOAD":   5,
	"CLIENT_STREAM":    100,
	"CLIENT_TIMEOUT":   101,
}

func (x ErrorReasonS2C) Enum() *ErrorReasonS2C {
	p := new(ErrorReasonS2C)
	*p = x
	return p
}

func (x ErrorReasonS2C) String() string {
	return proto.EnumName(ErrorReasonS2C_name, int32(x))
}

func (x *ErrorReasonS2C) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ErrorReasonS2C_value, data, "ErrorReasonS2C")
	if err != nil {
		return err
	}
	*x = ErrorReasonS2C(value)
	return nil
}

func (ErrorReasonS2C) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_39f66308029891ad, []int{3}
}

type TransportType int32

const (
	TransportType_NullTransport  TransportType = 0
	TransportType_MinTransport   TransportType = 1
	TransportType_Obfs4Transport TransportType = 2
)

var TransportType_name = map[int32]string{
	0: "NullTransport",
	1: "MinTransport",
	2: "Obfs4Transport",
}

var TransportType_value = map[string]int32{
	"NullTransport":  0,
	"MinTransport":   1,
	"Obfs4Transport": 2,
}

func (x TransportType) Enum() *TransportType {
	p := new(TransportType)
	*p = x
	return p
}

func (x TransportType) String() string {
	return proto.EnumName(TransportType_name, int32(x))
}

func (x *TransportType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(TransportType_value, data, "TransportType")
	if err != nil {
		return err
	}
	*x = TransportType(value)
	return nil
}

func (TransportType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_39f66308029891ad, []int{4}
}

type RegistrationSource int32

const (
	RegistrationSource_Detector RegistrationSource = 0
	RegistrationSource_API      RegistrationSource = 1
)

var RegistrationSource_name = map[int32]string{
	0: "Detector",
	1: "API",
}

var RegistrationSource_value = map[string]int32{
	"Detector": 0,
	"API":      1,
}

func (x RegistrationSource) Enum() *RegistrationSource {
	p := new(RegistrationSource)
	*p = x
	return p
}

func (x RegistrationSource) String() string {
	return proto.EnumName(RegistrationSource_name, int32(x))
}

func (x *RegistrationSource) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RegistrationSource_value, data, "RegistrationSource")
	if err != nil {
		return err
	}
	*x = RegistrationSource(value)
	return nil
}

func (RegistrationSource) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_39f66308029891ad, []int{5}
}

type PubKey struct {
	// A public key, as used by the station.
	Key                  []byte   `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Type                 *KeyType `protobuf:"varint,2,opt,name=type,enum=tapdance.KeyType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PubKey) Reset()         { *m = PubKey{} }
func (m *PubKey) String() string { return proto.CompactTextString(m) }
func (*PubKey) ProtoMessage()    {}
func (*PubKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_39f66308029891ad, []int{0}
}

func (m *PubKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PubKey.Unmarshal(m, b)
}
func (m *PubKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PubKey.Marshal(b, m, deterministic)
}
func (m *PubKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PubKey.Merge(m, src)
}
func (m *PubKey) XXX_Size() int {
	return xxx_messageInfo_PubKey.Size(m)
}
func (m *PubKey) XXX_DiscardUnknown() {
	xxx_messageInfo_PubKey.DiscardUnknown(m)
}

var xxx_messageInfo_PubKey proto.InternalMessageInfo

func (m *PubKey) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *PubKey) GetType() KeyType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return KeyType_AES_GCM_128
}

type TLSDecoySpec struct {
	// The hostname/SNI to use for this host
	//
	// The hostname is the only required field, although other
	// fields are expected to be present in most cases.
	Hostname *string `protobuf:"bytes,1,opt,name=hostname" json:"hostname,omitempty"`
	// The 32-bit ipv4 address, in network byte order
	//
	// If the IPv4 address is absent, then it may be resolved via
	// DNS by the client, or the client may discard this decoy spec
	// if local DNS is untrusted, or the service may be multihomed.
	Ipv4Addr *uint32 `protobuf:"fixed32,2,opt,name=ipv4addr" json:"ipv4addr,omitempty"`
	// The 128-bit ipv6 address, in network byte order
	Ipv6Addr []byte `protobuf:"bytes,6,opt,name=ipv6addr" json:"ipv6addr,omitempty"`
	// The Tapdance station public key to use when contacting this
	// decoy
	//
	// If omitted, the default station public key (if any) is used.
	Pubkey *PubKey `protobuf:"bytes,3,opt,name=pubkey" json:"pubkey,omitempty"`
	// The maximum duration, in milliseconds, to maintain an open
	// connection to this decoy (because the decoy may close the
	// connection itself after this length of time)
	//
	// If omitted, a default of 30,000 milliseconds is assumed.
	Timeout *uint32 `protobuf:"varint,4,opt,name=timeout" json:"timeout,omitempty"`
	// The maximum TCP window size to attempt to use for this decoy.
	//
	// If omitted, a default of 15360 is assumed.
	//
	// TODO: the default is based on the current heuristic of only
	// using decoys that permit windows of 15KB or larger.  If this
	// heuristic changes, then this default doesn't make sense.
	Tcpwin               *uint32  `protobuf:"varint,5,opt,name=tcpwin" json:"tcpwin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TLSDecoySpec) Reset()         { *m = TLSDecoySpec{} }
func (m *TLSDecoySpec) String() string { return proto.CompactTextString(m) }
func (*TLSDecoySpec) ProtoMessage()    {}
func (*TLSDecoySpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_39f66308029891ad, []int{1}
}

func (m *TLSDecoySpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TLSDecoySpec.Unmarshal(m, b)
}
func (m *TLSDecoySpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TLSDecoySpec.Marshal(b, m, deterministic)
}
func (m *TLSDecoySpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLSDecoySpec.Merge(m, src)
}
func (m *TLSDecoySpec) XXX_Size() int {
	return xxx_messageInfo_TLSDecoySpec.Size(m)
}
func (m *TLSDecoySpec) XXX_DiscardUnknown() {
	xxx_messageInfo_TLSDecoySpec.DiscardUnknown(m)
}

var xxx_messageInfo_TLSDecoySpec proto.InternalMessageInfo

func (m *TLSDecoySpec) GetHostname() string {
	if m != nil && m.Hostname != nil {
		return *m.Hostname
	}
	return ""
}

func (m *TLSDecoySpec) GetIpv4Addr() uint32 {
	if m != nil && m.Ipv4Addr != nil {
		return *m.Ipv4Addr
	}
	return 0
}

func (m *TLSDecoySpec) GetIpv6Addr() []byte {
	if m != nil {
		return m.Ipv6Addr
	}
	return nil
}

func (m *TLSDecoySpec) GetPubkey() *PubKey {
	if m != nil {
		return m.Pubkey
	}
	return nil
}

func (m *TLSDecoySpec) GetTimeout() uint32 {
	if m != nil && m.Timeout != nil {
		return *m.Timeout
	}
	return 0
}

func (m *TLSDecoySpec) GetTcpwin() uint32 {
	if m != nil && m.Tcpwin != nil {
		return *m.Tcpwin
	}
	return 0
}

type ClientConf struct {
	DecoyList            *DecoyList       `protobuf:"bytes,1,opt,name=decoy_list,json=decoyList" json:"decoy_list,omitempty"`
	Generation           *uint32          `protobuf:"varint,2,opt,name=generation" json:"generation,omitempty"`
	DefaultPubkey        *PubKey          `protobuf:"bytes,3,opt,name=default_pubkey,json=defaultPubkey" json:"default_pubkey,omitempty"`
	DarkDecoyBlocks      *DarkDecoyBlocks `protobuf:"bytes,4,opt,name=dark_decoy_blocks,json=darkDecoyBlocks" json:"dark_decoy_blocks,omitempty"`
	ConjurePubkey        *PubKey          `protobuf:"bytes,5,opt,name=conjure_pubkey,json=conjurePubkey" json:"conjure_pubkey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ClientConf) Reset()         { *m = ClientConf{} }
func (m *ClientConf) String() string { return proto.CompactTextString(m) }
func (*ClientConf) ProtoMessage()    {}
func (*ClientConf) Descriptor() ([]byte, []int) {
	return fileDescriptor_39f66308029891ad, []int{2}
}

func (m *ClientConf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientConf.Unmarshal(m, b)
}
func (m *ClientConf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientConf.Marshal(b, m, deterministic)
}
func (m *ClientConf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientConf.Merge(m, src)
}
func (m *ClientConf) XXX_Size() int {
	return xxx_messageInfo_ClientConf.Size(m)
}
func (m *ClientConf) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientConf.DiscardUnknown(m)
}

var xxx_messageInfo_ClientConf proto.InternalMessageInfo

func (m *ClientConf) GetDecoyList() *DecoyList {
	if m != nil {
		return m.DecoyList
	}
	return nil
}

func (m *ClientConf) GetGeneration() uint32 {
	if m != nil && m.Generation != nil {
		return *m.Generation
	}
	return 0
}

func (m *ClientConf) GetDefaultPubkey() *PubKey {
	if m != nil {
		return m.DefaultPubkey
	}
	return nil
}

func (m *ClientConf) GetDarkDecoyBlocks() *DarkDecoyBlocks {
	if m != nil {
		return m.DarkDecoyBlocks
	}
	return nil
}

func (m *ClientConf) GetConjurePubkey() *PubKey {
	if m != nil {
		return m.ConjurePubkey
	}
	return nil
}

type DecoyList struct {
	TlsDecoys            []*TLSDecoySpec `protobuf:"bytes,1,rep,name=tls_decoys,json=tlsDecoys" json:"tls_decoys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DecoyList) Reset()         { *m = DecoyList{} }
func (m *DecoyList) String() string { return proto.CompactTextString(m) }
func (*DecoyList) ProtoMessage()    {}
func (*DecoyList) Descriptor() ([]byte, []int) {
	return fileDescriptor_39f66308029891ad, []int{3}
}

func (m *DecoyList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecoyList.Unmarshal(m, b)
}
func (m *DecoyList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecoyList.Marshal(b, m, deterministic)
}
func (m *DecoyList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecoyList.Merge(m, src)
}
func (m *DecoyList) XXX_Size() int {
	return xxx_messageInfo_DecoyList.Size(m)
}
func (m *DecoyList) XXX_DiscardUnknown() {
	xxx_messageInfo_DecoyList.DiscardUnknown(m)
}

var xxx_messageInfo_DecoyList proto.InternalMessageInfo

func (m *DecoyList) GetTlsDecoys() []*TLSDecoySpec {
	if m != nil {
		return m.TlsDecoys
	}
	return nil
}

type DarkDecoyBlocks struct {
	Blocks               []string `protobuf:"bytes,1,rep,name=blocks" json:"blocks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DarkDecoyBlocks) Reset()         { *m = DarkDecoyBlocks{} }
func (m *DarkDecoyBlocks) String() string { return proto.CompactTextString(m) }
func (*DarkDecoyBlocks) ProtoMessage()    {}
func (*DarkDecoyBlocks) Descriptor() ([]byte, []int) {
	return fileDescriptor_39f66308029891ad, []int{4}
}

func (m *DarkDecoyBlocks) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DarkDecoyBlocks.Unmarshal(m, b)
}
func (m *DarkDecoyBlocks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DarkDecoyBlocks.Marshal(b, m, deterministic)
}
func (m *DarkDecoyBlocks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DarkDecoyBlocks.Merge(m, src)
}
func (m *DarkDecoyBlocks) XXX_Size() int {
	return xxx_messageInfo_DarkDecoyBlocks.Size(m)
}
func (m *DarkDecoyBlocks) XXX_DiscardUnknown() {
	xxx_messageInfo_DarkDecoyBlocks.DiscardUnknown(m)
}

var xxx_messageInfo_DarkDecoyBlocks proto.InternalMessageInfo

func (m *DarkDecoyBlocks) GetBlocks() []string {
	if m != nil {
		return m.Blocks
	}
	return nil
}

type StationToClient struct {
	// Should accompany (at least) SESSION_INIT and CONFIRM_RECONNECT.
	ProtocolVersion *uint32 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion" json:"protocol_version,omitempty"`
	// There might be a state transition. May be absent; absence should be
	// treated identically to NO_CHANGE.
	StateTransition *S2C_Transition `protobuf:"varint,2,opt,name=state_transition,json=stateTransition,enum=tapdance.S2C_Transition" json:"state_transition,omitempty"`
	// The station can send client config info piggybacked
	// on any message, as it sees fit
	ConfigInfo *ClientConf `protobuf:"bytes,3,opt,name=config_info,json=configInfo" json:"config_info,omitempty"`
	// If state_transition == S2C_ERROR, this field is the explanation.
	ErrReason *ErrorReasonS2C `protobuf:"varint,4,opt,name=err_reason,json=errReason,enum=tapdance.ErrorReasonS2C" json:"err_reason,omitempty"`
	// Signals client to stop connecting for following amount of seconds
	TmpBackoff *uint32 `protobuf:"varint,5,opt,name=tmp_backoff,json=tmpBackoff" json:"tmp_backoff,omitempty"`
	// Sent in SESSION_INIT, identifies the station that picked up
	StationId *string `protobuf:"bytes,6,opt,name=station_id,json=stationId" json:"station_id,omitempty"`
	// Random-sized junk to defeat packet size fingerprinting.
	Padding              []byte   `protobuf:"bytes,100,opt,name=padding" json:"padding,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StationToClient) Reset()         { *m = StationToClient{} }
func (m *StationToClient) String() string { return proto.CompactTextString(m) }
func (*StationToClient) ProtoMessage()    {}
func (*StationToClient) Descriptor() ([]byte, []int) {
	return fileDescriptor_39f66308029891ad, []int{5}
}

func (m *StationToClient) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StationToClient.Unmarshal(m, b)
}
func (m *StationToClient) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StationToClient.Marshal(b, m, deterministic)
}
func (m *StationToClient) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StationToClient.Merge(m, src)
}
func (m *StationToClient) XXX_Size() int {
	return xxx_messageInfo_StationToClient.Size(m)
}
func (m *StationToClient) XXX_DiscardUnknown() {
	xxx_messageInfo_StationToClient.DiscardUnknown(m)
}

var xxx_messageInfo_StationToClient proto.InternalMessageInfo

func (m *StationToClient) GetProtocolVersion() uint32 {
	if m != nil && m.ProtocolVersion != nil {
		return *m.ProtocolVersion
	}
	return 0
}

func (m *StationToClient) GetStateTransition() S2C_Transition {
	if m != nil && m.StateTransition != nil {
		return *m.StateTransition
	}
	return S2C_Transition_S2C_NO_CHANGE
}

func (m *StationToClient) GetConfigInfo() *ClientConf {
	if m != nil {
		return m.ConfigInfo
	}
	return nil
}

func (m *StationToClient) GetErrReason() ErrorReasonS2C {
	if m != nil && m.ErrReason != nil {
		return *m.ErrReason
	}
	return ErrorReasonS2C_NO_ERROR
}

func (m *StationToClient) GetTmpBackoff() uint32 {
	if m != nil && m.TmpBackoff != nil {
		return *m.TmpBackoff
	}
	return 0
}

func (m *StationToClient) GetStationId() string {
	if m != nil && m.StationId != nil {
		return *m.StationId
	}
	return ""
}

func (m *StationToClient) GetPadding() []byte {
	if m != nil {
		return m.Padding
	}
	return nil
}

type RegistrationFlags struct {
	UploadOnly           *bool    `protobuf:"varint,1,opt,name=upload_only,json=uploadOnly" json:"upload_only,omitempty"`
	DarkDecoy            *bool    `protobuf:"varint,2,opt,name=dark_decoy,json=darkDecoy" json:"dark_decoy,omitempty"`
	ProxyHeader          *bool    `protobuf:"varint,3,opt,name=proxy_header,json=proxyHeader" json:"proxy_header,omitempty"`
	Use_TIL              *bool    `protobuf:"varint,4,opt,name=use_TIL,json=useTIL" json:"use_TIL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegistrationFlags) Reset()         { *m = RegistrationFlags{} }
func (m *RegistrationFlags) String() string { return proto.CompactTextString(m) }
func (*RegistrationFlags) ProtoMessage()    {}
func (*RegistrationFlags) Descriptor() ([]byte, []int) {
	return fileDescriptor_39f66308029891ad, []int{6}
}

func (m *RegistrationFlags) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegistrationFlags.Unmarshal(m, b)
}
func (m *RegistrationFlags) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegistrationFlags.Marshal(b, m, deterministic)
}
func (m *RegistrationFlags) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistrationFlags.Merge(m, src)
}
func (m *RegistrationFlags) XXX_Size() int {
	return xxx_messageInfo_RegistrationFlags.Size(m)
}
func (m *RegistrationFlags) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistrationFlags.DiscardUnknown(m)
}

var xxx_messageInfo_RegistrationFlags proto.InternalMessageInfo

func (m *RegistrationFlags) GetUploadOnly() bool {
	if m != nil && m.UploadOnly != nil {
		return *m.UploadOnly
	}
	return false
}

func (m *RegistrationFlags) GetDarkDecoy() bool {
	if m != nil && m.DarkDecoy != nil {
		return *m.DarkDecoy
	}
	return false
}

func (m *RegistrationFlags) GetProxyHeader() bool {
	if m != nil && m.ProxyHeader != nil {
		return *m.ProxyHeader
	}
	return false
}

func (m *RegistrationFlags) GetUse_TIL() bool {
	if m != nil && m.Use_TIL != nil {
		return *m.Use_TIL
	}
	return false
}

type ClientToStation struct {
	ProtocolVersion *uint32 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion" json:"protocol_version,omitempty"`
	// The client reports its decoy list's version number here, which the
	// station can use to decide whether to send an updated one. The station
	// should always send a list if this field is set to 0.
	DecoyListGeneration *uint32         `protobuf:"varint,2,opt,name=decoy_list_generation,json=decoyListGeneration" json:"decoy_list_generation,omitempty"`
	StateTransition     *C2S_Transition `protobuf:"varint,3,opt,name=state_transition,json=stateTransition,enum=tapdance.C2S_Transition" json:"state_transition,omitempty"`
	// The position in the overall session's upload sequence where the current
	// YIELD=>ACQUIRE switchover is happening.
	UploadSync *uint64 `protobuf:"varint,4,opt,name=upload_sync,json=uploadSync" json:"upload_sync,omitempty"`
	// List of decoys that client have unsuccessfully tried in current session.
	// Could be sent in chunks
	FailedDecoys []string      `protobuf:"bytes,10,rep,name=failed_decoys,json=failedDecoys" json:"failed_decoys,omitempty"`
	Stats        *SessionStats `protobuf:"bytes,11,opt,name=stats" json:"stats,omitempty"`
	// NullTransport, MinTransport, Obfs4Transport, etc. Transport type we want from phantom proxy
	Transport *TransportType `protobuf:"varint,12,opt,name=transport,enum=tapdance.TransportType" json:"transport,omitempty"`
	// Station is only required to check this variable during session initialization.
	// If set, station must facilitate connection to said target by itself, i.e. write into squid
	// socket an HTTP/SOCKS/any other connection request.
	// covert_address must have exactly one ':' colon, that separates host (literal IP address or
	// resolvable hostname) and port
	// TODO: make it required for initialization, and stop connecting any client straight to squid?
	CovertAddress *string `protobuf:"bytes,20,opt,name=covert_address,json=covertAddress" json:"covert_address,omitempty"`
	// Used in dark decoys to signal which dark decoy it will connect to.
	MaskedDecoyServerName *string `protobuf:"bytes,21,opt,name=masked_decoy_server_name,json=maskedDecoyServerName" json:"masked_decoy_server_name,omitempty"`
	// Used to indicate to server if client is registering v4, v6 or both
	V6Support *bool `protobuf:"varint,22,opt,name=v6_support,json=v6Support" json:"v6_support,omitempty"`
	V4Support *bool `protobuf:"varint,23,opt,name=v4_support,json=v4Support" json:"v4_support,omitempty"`
	// A collection of optional flags for the registration.
	Flags *RegistrationFlags `protobuf:"bytes,24,opt,name=flags" json:"flags,omitempty"`
	// Random-sized junk to defeat packet size fingerprinting.
	Padding              []byte   `protobuf:"bytes,100,opt,name=padding" json:"padding,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientToStation) Reset()         { *m = ClientToStation{} }
func (m *ClientToStation) String() string { return proto.CompactTextString(m) }
func (*ClientToStation) ProtoMessage()    {}
func (*ClientToStation) Descriptor() ([]byte, []int) {
	return fileDescriptor_39f66308029891ad, []int{7}
}

func (m *ClientToStation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientToStation.Unmarshal(m, b)
}
func (m *ClientToStation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientToStation.Marshal(b, m, deterministic)
}
func (m *ClientToStation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientToStation.Merge(m, src)
}
func (m *ClientToStation) XXX_Size() int {
	return xxx_messageInfo_ClientToStation.Size(m)
}
func (m *ClientToStation) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientToStation.DiscardUnknown(m)
}

var xxx_messageInfo_ClientToStation proto.InternalMessageInfo

func (m *ClientToStation) GetProtocolVersion() uint32 {
	if m != nil && m.ProtocolVersion != nil {
		return *m.ProtocolVersion
	}
	return 0
}

func (m *ClientToStation) GetDecoyListGeneration() uint32 {
	if m != nil && m.DecoyListGeneration != nil {
		return *m.DecoyListGeneration
	}
	return 0
}

func (m *ClientToStation) GetStateTransition() C2S_Transition {
	if m != nil && m.StateTransition != nil {
		return *m.StateTransition
	}
	return C2S_Transition_C2S_NO_CHANGE
}

func (m *ClientToStation) GetUploadSync() uint64 {
	if m != nil && m.UploadSync != nil {
		return *m.UploadSync
	}
	return 0
}

func (m *ClientToStation) GetFailedDecoys() []string {
	if m != nil {
		return m.FailedDecoys
	}
	return nil
}

func (m *ClientToStation) GetStats() *SessionStats {
	if m != nil {
		return m.Stats
	}
	return nil
}

func (m *ClientToStation) GetTransport() TransportType {
	if m != nil && m.Transport != nil {
		return *m.Transport
	}
	return TransportType_Null
}

func (m *ClientToStation) GetCovertAddress() string {
	if m != nil && m.CovertAddress != nil {
		return *m.CovertAddress
	}
	return ""
}

func (m *ClientToStation) GetMaskedDecoyServerName() string {
	if m != nil && m.MaskedDecoyServerName != nil {
		return *m.MaskedDecoyServerName
	}
	return ""
}

func (m *ClientToStation) GetV6Support() bool {
	if m != nil && m.V6Support != nil {
		return *m.V6Support
	}
	return false
}

func (m *ClientToStation) GetV4Support() bool {
	if m != nil && m.V4Support != nil {
		return *m.V4Support
	}
	return false
}

func (m *ClientToStation) GetFlags() *RegistrationFlags {
	if m != nil {
		return m.Flags
	}
	return nil
}

func (m *ClientToStation) GetPadding() []byte {
	if m != nil {
		return m.Padding
	}
	return nil
}

// Message type used as the request body when registering via the HTTP API.
// This message is assumed to be sent via TLS, meaning that sending the secret outright is acceptable.
type ClientToAPI struct {
	// The secret that will be used when forming phantom connections.
	Secret []byte `protobuf:"bytes,1,opt,name=secret" json:"secret,omitempty"`
	// The ClientToStation payload; the same as used in decoy registrations.
	RegistrationPayload  *ClientToStation `protobuf:"bytes,2,opt,name=registration_payload,json=registrationPayload" json:"registration_payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ClientToAPI) Reset()         { *m = ClientToAPI{} }
func (m *ClientToAPI) String() string { return proto.CompactTextString(m) }
func (*ClientToAPI) ProtoMessage()    {}
func (*ClientToAPI) Descriptor() ([]byte, []int) {
	return fileDescriptor_39f66308029891ad, []int{8}
}

func (m *ClientToAPI) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientToAPI.Unmarshal(m, b)
}
func (m *ClientToAPI) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientToAPI.Marshal(b, m, deterministic)
}
func (m *ClientToAPI) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientToAPI.Merge(m, src)
}
func (m *ClientToAPI) XXX_Size() int {
	return xxx_messageInfo_ClientToAPI.Size(m)
}
func (m *ClientToAPI) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientToAPI.DiscardUnknown(m)
}

var xxx_messageInfo_ClientToAPI proto.InternalMessageInfo

func (m *ClientToAPI) GetSecret() []byte {
	if m != nil {
		return m.Secret
	}
	return nil
}

func (m *ClientToAPI) GetRegistrationPayload() *ClientToStation {
	if m != nil {
		return m.RegistrationPayload
	}
	return nil
}

type ZMQPayload struct {
	SharedSecret         []byte              `protobuf:"bytes,1,opt,name=shared_secret,json=sharedSecret" json:"shared_secret,omitempty"`
	RegistrationPayload  *ClientToStation    `protobuf:"bytes,3,opt,name=registration_payload,json=registrationPayload" json:"registration_payload,omitempty"`
	RegistrationSource   *RegistrationSource `protobuf:"varint,4,opt,name=registration_source,json=registrationSource,enum=tapdance.RegistrationSource" json:"registration_source,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ZMQPayload) Reset()         { *m = ZMQPayload{} }
func (m *ZMQPayload) String() string { return proto.CompactTextString(m) }
func (*ZMQPayload) ProtoMessage()    {}
func (*ZMQPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_39f66308029891ad, []int{9}
}

func (m *ZMQPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZMQPayload.Unmarshal(m, b)
}
func (m *ZMQPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZMQPayload.Marshal(b, m, deterministic)
}
func (m *ZMQPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZMQPayload.Merge(m, src)
}
func (m *ZMQPayload) XXX_Size() int {
	return xxx_messageInfo_ZMQPayload.Size(m)
}
func (m *ZMQPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_ZMQPayload.DiscardUnknown(m)
}

var xxx_messageInfo_ZMQPayload proto.InternalMessageInfo

func (m *ZMQPayload) GetSharedSecret() []byte {
	if m != nil {
		return m.SharedSecret
	}
	return nil
}

func (m *ZMQPayload) GetRegistrationPayload() *ClientToStation {
	if m != nil {
		return m.RegistrationPayload
	}
	return nil
}

func (m *ZMQPayload) GetRegistrationSource() RegistrationSource {
	if m != nil && m.RegistrationSource != nil {
		return *m.RegistrationSource
	}
	return RegistrationSource_Detector
}

type SessionStats struct {
	FailedDecoysAmount *uint32 `protobuf:"varint,20,opt,name=failed_decoys_amount,json=failedDecoysAmount" json:"failed_decoys_amount,omitempty"`
	// Applicable to whole session:
	TotalTimeToConnect *uint32 `protobuf:"varint,31,opt,name=total_time_to_connect,json=totalTimeToConnect" json:"total_time_to_connect,omitempty"`
	// Last (i.e. successful) decoy:
	RttToStation         *uint32  `protobuf:"varint,33,opt,name=rtt_to_station,json=rttToStation" json:"rtt_to_station,omitempty"`
	TlsToDecoy           *uint32  `protobuf:"varint,38,opt,name=tls_to_decoy,json=tlsToDecoy" json:"tls_to_decoy,omitempty"`
	TcpToDecoy           *uint32  `protobuf:"varint,39,opt,name=tcp_to_decoy,json=tcpToDecoy" json:"tcp_to_decoy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionStats) Reset()         { *m = SessionStats{} }
func (m *SessionStats) String() string { return proto.CompactTextString(m) }
func (*SessionStats) ProtoMessage()    {}
func (*SessionStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_39f66308029891ad, []int{10}
}

func (m *SessionStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionStats.Unmarshal(m, b)
}
func (m *SessionStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionStats.Marshal(b, m, deterministic)
}
func (m *SessionStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionStats.Merge(m, src)
}
func (m *SessionStats) XXX_Size() int {
	return xxx_messageInfo_SessionStats.Size(m)
}
func (m *SessionStats) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionStats.DiscardUnknown(m)
}

var xxx_messageInfo_SessionStats proto.InternalMessageInfo

func (m *SessionStats) GetFailedDecoysAmount() uint32 {
	if m != nil && m.FailedDecoysAmount != nil {
		return *m.FailedDecoysAmount
	}
	return 0
}

func (m *SessionStats) GetTotalTimeToConnect() uint32 {
	if m != nil && m.TotalTimeToConnect != nil {
		return *m.TotalTimeToConnect
	}
	return 0
}

func (m *SessionStats) GetRttToStation() uint32 {
	if m != nil && m.RttToStation != nil {
		return *m.RttToStation
	}
	return 0
}

func (m *SessionStats) GetTlsToDecoy() uint32 {
	if m != nil && m.TlsToDecoy != nil {
		return *m.TlsToDecoy
	}
	return 0
}

func (m *SessionStats) GetTcpToDecoy() uint32 {
	if m != nil && m.TcpToDecoy != nil {
		return *m.TcpToDecoy
	}
	return 0
}

func init() {
	proto.RegisterEnum("tapdance.KeyType", KeyType_name, KeyType_value)
	proto.RegisterEnum("tapdance.C2S_Transition", C2S_Transition_name, C2S_Transition_value)
	proto.RegisterEnum("tapdance.S2C_Transition", S2C_Transition_name, S2C_Transition_value)
	proto.RegisterEnum("tapdance.ErrorReasonS2C", ErrorReasonS2C_name, ErrorReasonS2C_value)
	proto.RegisterEnum("tapdance.TransportType", TransportType_name, TransportType_value)
	proto.RegisterEnum("tapdance.RegistrationSource", RegistrationSource_name, RegistrationSource_value)
	proto.RegisterType((*PubKey)(nil), "tapdance.PubKey")
	proto.RegisterType((*TLSDecoySpec)(nil), "tapdance.TLSDecoySpec")
	proto.RegisterType((*ClientConf)(nil), "tapdance.ClientConf")
	proto.RegisterType((*DecoyList)(nil), "tapdance.DecoyList")
	proto.RegisterType((*DarkDecoyBlocks)(nil), "tapdance.DarkDecoyBlocks")
	proto.RegisterType((*StationToClient)(nil), "tapdance.StationToClient")
	proto.RegisterType((*RegistrationFlags)(nil), "tapdance.RegistrationFlags")
	proto.RegisterType((*ClientToStation)(nil), "tapdance.ClientToStation")
	proto.RegisterType((*ClientToAPI)(nil), "tapdance.ClientToAPI")
	proto.RegisterType((*ZMQPayload)(nil), "tapdance.ZMQPayload")
	proto.RegisterType((*SessionStats)(nil), "tapdance.SessionStats")
}

func init() { proto.RegisterFile("signalling.proto", fileDescriptor_39f66308029891ad) }

var fileDescriptor_39f66308029891ad = []byte{
	// 1408 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0x5d, 0x72, 0xdb, 0x46,
	0x12, 0x16, 0xf4, 0xcf, 0xe6, 0x1f, 0x34, 0xfa, 0x83, 0xd7, 0xf6, 0x5a, 0xe6, 0xae, 0x77, 0x65,
	0x79, 0xcb, 0xb5, 0x66, 0x49, 0x72, 0x5e, 0x69, 0x08, 0xb6, 0x59, 0xa6, 0x08, 0x7a, 0x00, 0xbb,
	0x62, 0xe7, 0x61, 0x0a, 0x02, 0x86, 0x32, 0x22, 0x08, 0x83, 0xc2, 0x0c, 0x95, 0xf0, 0x14, 0x79,
	0x4d, 0xee, 0x90, 0x33, 0xe4, 0x02, 0xae, 0xca, 0x0d, 0xf2, 0x9c, 0x63, 0x24, 0x35, 0x33, 0x20,
	0x41, 0x4a, 0x8e, 0x53, 0xc9, 0x1b, 0xfb, 0xeb, 0xee, 0xe9, 0xbf, 0xaf, 0x1b, 0x04, 0x93, 0xc7,
	0xe7, 0x69, 0x90, 0x24, 0x71, 0x7a, 0xfe, 0x38, 0xcb, 0x99, 0x60, 0x68, 0x5d, 0x04, 0x59, 0x14,
	0xa4, 0x21, 0x6d, 0x75, 0x60, 0x75, 0x30, 0x3a, 0x7b, 0x45, 0xc7, 0xc8, 0x84, 0xa5, 0x0b, 0x3a,
	0xb6, 0x8c, 0x3d, 0x63, 0xbf, 0x86, 0xe5, 0x4f, 0xf4, 0x00, 0x96, 0xc5, 0x38, 0xa3, 0xd6, 0xe2,
	0x9e, 0xb1, 0xdf, 0x68, 0x6f, 0x3c, 0x9e, 0x38, 0x3d, 0x7e, 0x45, 0xc7, 0xfe, 0x38, 0xa3, 0x58,
	0xa9, 0x5b, 0x3f, 0x19, 0x50, 0xf3, 0x7b, 0xde, 0x09, 0x0d, 0xd9, 0xd8, 0xcb, 0x68, 0x88, 0xfe,
	0x01, 0xeb, 0x1f, 0x18, 0x17, 0x69, 0x70, 0x49, 0xd5, 0x73, 0x15, 0x3c, 0x95, 0xa5, 0x2e, 0xce,
	0xae, 0x0e, 0x83, 0x28, 0xca, 0xd5, 0xbb, 0x6b, 0x78, 0x2a, 0x17, 0xba, 0x63, 0xa5, 0x5b, 0x55,
	0x69, 0x4c, 0x65, 0xb4, 0x0f, 0xab, 0xd9, 0xe8, 0x4c, 0x26, 0xb8, 0xb4, 0x67, 0xec, 0x57, 0xdb,
	0x66, 0x99, 0x8d, 0xce, 0x1f, 0x17, 0x7a, 0x64, 0xc1, 0x9a, 0x88, 0x2f, 0x29, 0x1b, 0x09, 0x6b,
	0x79, 0xcf, 0xd8, 0xaf, 0xe3, 0x89, 0x88, 0x76, 0x60, 0x55, 0x84, 0xd9, 0x37, 0x71, 0x6a, 0xad,
	0x28, 0x45, 0x21, 0xb5, 0x7e, 0x58, 0x04, 0xb0, 0x93, 0x98, 0xa6, 0xc2, 0x66, 0xe9, 0x10, 0xb5,
	0x01, 0x22, 0x59, 0x0b, 0x49, 0x62, 0x2e, 0x54, 0x01, 0xd5, 0xf6, 0x66, 0x19, 0x4e, 0xd5, 0xd9,
	0x8b, 0xb9, 0xc0, 0x95, 0x68, 0xf2, 0x13, 0xfd, 0x13, 0xe0, 0x9c, 0xa6, 0x34, 0x0f, 0x44, 0xcc,
	0x52, 0x55, 0x58, 0x1d, 0xcf, 0x20, 0xe8, 0x29, 0x34, 0x22, 0x3a, 0x0c, 0x46, 0x89, 0x20, 0x7f,
	0x52, 0x46, 0xbd, 0xb0, 0x1b, 0xe8, 0x6a, 0x1c, 0xd8, 0x88, 0x82, 0xfc, 0x82, 0xe8, 0x8c, 0xce,
	0x12, 0x16, 0x5e, 0x70, 0x55, 0x57, 0xb5, 0x7d, 0x6b, 0x26, 0xa7, 0x20, 0xbf, 0x50, 0x79, 0x3d,
	0x53, 0x06, 0xb8, 0x19, 0xcd, 0x03, 0x32, 0x7e, 0xc8, 0xd2, 0xaf, 0x47, 0x39, 0x9d, 0xc4, 0x5f,
	0xf9, 0xa3, 0xf8, 0x85, 0x9d, 0x8e, 0xdf, 0x7a, 0x06, 0x95, 0x69, 0xc1, 0xe8, 0x08, 0x40, 0x24,
	0x5c, 0xe7, 0xc2, 0x2d, 0x63, 0x6f, 0x69, 0xbf, 0xda, 0xde, 0x29, 0x5f, 0x98, 0x25, 0x01, 0xae,
	0x88, 0x84, 0x2b, 0x89, 0xb7, 0x1e, 0x42, 0xf3, 0x5a, 0x82, 0x72, 0x14, 0x45, 0x2d, 0xf2, 0x95,
	0x0a, 0x2e, 0xa4, 0xd6, 0xc7, 0x45, 0x68, 0x7a, 0x42, 0xf5, 0xcc, 0x67, 0x7a, 0x26, 0xe8, 0x21,
	0x98, 0x8a, 0xb5, 0x21, 0x4b, 0xc8, 0x15, 0xcd, 0xb9, 0xec, 0xb0, 0xa1, 0x3a, 0xdc, 0x9c, 0xe0,
	0x6f, 0x35, 0x8c, 0x6c, 0x30, 0xb9, 0x08, 0x04, 0x25, 0x22, 0x0f, 0x52, 0x1e, 0x4f, 0x87, 0xd1,
	0x68, 0x5b, 0x65, 0x9a, 0x5e, 0xdb, 0x26, 0xfe, 0x54, 0x8f, 0x9b, 0xca, 0xa3, 0x04, 0xd0, 0x11,
	0x54, 0x43, 0x96, 0x0e, 0xe3, 0x73, 0x12, 0xa7, 0x43, 0x56, 0x0c, 0x6a, 0xab, 0xf4, 0x2f, 0xa9,
	0x82, 0x41, 0x1b, 0x76, 0xd3, 0x21, 0x43, 0x4f, 0x01, 0x68, 0x9e, 0x93, 0x9c, 0x06, 0x9c, 0xa5,
	0x6a, 0x44, 0x73, 0x51, 0x9d, 0x3c, 0x67, 0x39, 0x56, 0x4a, 0xaf, 0x6d, 0xe3, 0x0a, 0xcd, 0x0b,
	0x09, 0xdd, 0x83, 0xaa, 0xb8, 0xcc, 0xc8, 0x59, 0x10, 0x5e, 0xb0, 0xe1, 0xb0, 0xe0, 0x26, 0x88,
	0xcb, 0xec, 0x99, 0x46, 0xd0, 0x5d, 0x00, 0xae, 0x7b, 0x42, 0xe2, 0x48, 0x6d, 0x46, 0x05, 0x57,
	0x0a, 0xa4, 0x1b, 0x49, 0xc2, 0x67, 0x41, 0x14, 0xc5, 0xe9, 0xb9, 0x15, 0xa9, 0xad, 0x99, 0x88,
	0xad, 0xef, 0x0c, 0xd8, 0xc0, 0xf4, 0x3c, 0xe6, 0x42, 0xd3, 0xf0, 0x79, 0x12, 0x9c, 0x73, 0x19,
	0x6f, 0x94, 0x25, 0x2c, 0x88, 0x08, 0x4b, 0x13, 0xbd, 0xf0, 0xeb, 0x18, 0x34, 0xe4, 0xa6, 0xc9,
	0x58, 0xc6, 0x2b, 0x39, 0xa7, 0xfa, 0xb7, 0x8e, 0x2b, 0x53, 0x46, 0xa1, 0xfb, 0x50, 0xcb, 0x72,
	0xf6, 0xed, 0x98, 0x7c, 0xa0, 0x41, 0x44, 0x73, 0xd5, 0xa0, 0x75, 0x5c, 0x55, 0xd8, 0x4b, 0x05,
	0xa1, 0x5d, 0x58, 0x1b, 0x71, 0x4a, 0xfc, 0x6e, 0x4f, 0x35, 0x62, 0x1d, 0xaf, 0x8e, 0x38, 0xf5,
	0xbb, 0xbd, 0xd6, 0xc7, 0x65, 0x68, 0xea, 0xfe, 0xf9, 0xac, 0x98, 0xf3, 0x5f, 0x99, 0x6f, 0x1b,
	0xb6, 0xcb, 0xd5, 0x24, 0x37, 0x36, 0x6e, 0x73, 0xba, 0x90, 0x2f, 0xca, 0xd5, 0xfb, 0x14, 0x27,
	0x96, 0xae, 0x4f, 0xc7, 0x6e, 0x7b, 0x9f, 0xe5, 0x44, 0xd9, 0x33, 0x3e, 0x4e, 0x43, 0x55, 0xd4,
	0xf2, 0xa4, 0x67, 0xde, 0x38, 0x0d, 0xd1, 0xbf, 0xa0, 0x3e, 0x0c, 0xe2, 0x84, 0x46, 0x93, 0xed,
	0x00, 0xc5, 0xeb, 0x9a, 0x06, 0xf5, 0x22, 0xa0, 0xff, 0xc1, 0x8a, 0x7c, 0x98, 0x5b, 0x55, 0xc5,
	0xa9, 0x99, 0xd5, 0xf1, 0x28, 0x97, 0x05, 0xca, 0x96, 0x70, 0xac, 0x8d, 0xd0, 0x11, 0x54, 0x54,
	0xca, 0x19, 0xcb, 0x85, 0x55, 0x53, 0x19, 0xef, 0xce, 0x2c, 0xdb, 0x44, 0xa5, 0x2e, 0x71, 0x69,
	0x89, 0x1e, 0xc8, 0x55, 0xbf, 0xa2, 0xb9, 0x20, 0xf2, 0x70, 0x52, 0xce, 0xad, 0x2d, 0xc5, 0x98,
	0xba, 0x46, 0x3b, 0x1a, 0x44, 0x4f, 0xc1, 0xba, 0x0c, 0xf8, 0xc5, 0x24, 0x61, 0xc2, 0x69, 0x7e,
	0x45, 0x73, 0xa2, 0x8e, 0xf6, 0xb6, 0x72, 0xd8, 0xd6, 0x7a, 0xbd, 0xd2, 0x4a, 0xdb, 0x97, 0x17,
	0xfc, 0x2e, 0xc0, 0xd5, 0x31, 0xe1, 0xa3, 0x4c, 0xe5, 0xb5, 0xa3, 0xd9, 0x71, 0x75, 0xec, 0x69,
	0x40, 0xa9, 0x0f, 0xa7, 0xea, 0xdd, 0x42, 0x7d, 0x38, 0x51, 0x3f, 0x81, 0x95, 0xa1, 0x64, 0xa1,
	0x65, 0xa9, 0x16, 0xdc, 0x2e, 0x0b, 0xba, 0x41, 0x54, 0xac, 0x2d, 0x3f, 0xc3, 0x6f, 0x0e, 0xd5,
	0x09, 0x99, 0x3a, 0x83, 0xae, 0x3c, 0x2a, 0x9c, 0x86, 0x39, 0x15, 0xc5, 0x47, 0xac, 0x90, 0x50,
	0x0f, 0xb6, 0xf2, 0x99, 0xc7, 0x49, 0x16, 0x8c, 0xe5, 0xdc, 0x14, 0x69, 0xe6, 0xce, 0xe8, 0x35,
	0x66, 0xe2, 0xcd, 0x59, 0xb7, 0x81, 0xf6, 0x6a, 0xfd, 0x6c, 0x00, 0xbc, 0x3f, 0x7d, 0x5d, 0x88,
	0x72, 0xf0, 0xfc, 0x43, 0x90, 0xd3, 0x88, 0xcc, 0xc5, 0xae, 0x69, 0xd0, 0xfb, 0x7c, 0x06, 0x4b,
	0x7f, 0x27, 0x03, 0x74, 0x0a, 0x73, 0x30, 0xe1, 0x6c, 0x94, 0x87, 0xb4, 0x38, 0x39, 0x77, 0x3e,
	0xdd, 0x51, 0x4f, 0xd9, 0x60, 0x94, 0xdf, 0xc0, 0x5a, 0xbf, 0x18, 0x50, 0x9b, 0xe5, 0x1f, 0xfa,
	0x3f, 0x6c, 0xcd, 0x71, 0x99, 0x04, 0x97, 0x6c, 0x94, 0x0a, 0xc5, 0xa3, 0x3a, 0x46, 0xb3, 0x94,
	0xee, 0x28, 0x0d, 0x7a, 0x02, 0xdb, 0x82, 0x89, 0x20, 0x21, 0xf2, 0x53, 0x4b, 0x04, 0x23, 0x21,
	0x4b, 0x53, 0x1a, 0x0a, 0xeb, 0x9e, 0x76, 0x51, 0x4a, 0x3f, 0xbe, 0xa4, 0x3e, 0xb3, 0xb5, 0x06,
	0xfd, 0x1b, 0x1a, 0xb9, 0x10, 0xd2, 0xb6, 0xb8, 0x64, 0xd6, 0x7d, 0x65, 0x5b, 0xcb, 0xc5, 0xcc,
	0x6d, 0xd8, 0x83, 0x9a, 0xfc, 0xe2, 0x08, 0x56, 0x1c, 0xa3, 0xff, 0x14, 0xc7, 0x31, 0xe1, 0x3e,
	0xd3, 0xd7, 0x48, 0x5a, 0x84, 0x59, 0x69, 0xf1, 0xdf, 0xc2, 0x22, 0xcc, 0x0a, 0x8b, 0x83, 0x47,
	0xb0, 0x56, 0xfc, 0x61, 0x41, 0x4d, 0xa8, 0x76, 0x1c, 0x8f, 0xbc, 0xb0, 0x4f, 0xc9, 0x93, 0xf6,
	0x17, 0xe6, 0xfb, 0x59, 0xa0, 0x7d, 0x74, 0x6c, 0x7e, 0x75, 0xf0, 0xab, 0x01, 0x8d, 0xf9, 0x63,
	0x80, 0x36, 0xa0, 0x2e, 0x91, 0xbe, 0x4b, 0xec, 0x97, 0x9d, 0xfe, 0x0b, 0xc7, 0x5c, 0x40, 0x5b,
	0x60, 0x4a, 0xc8, 0x73, 0x3c, 0xaf, 0xeb, 0xf6, 0x49, 0xb7, 0xdf, 0xf5, 0x4d, 0x03, 0xdd, 0x86,
	0xdd, 0x59, 0xd4, 0x76, 0xdf, 0x3a, 0xd8, 0xd7, 0xca, 0x2a, 0xb2, 0x60, 0x4b, 0x2a, 0x9d, 0x2f,
	0x07, 0x8e, 0xed, 0x13, 0xec, 0xd8, 0x6e, 0xbf, 0xef, 0xd8, 0xbe, 0xb9, 0x88, 0xb6, 0x61, 0x63,
	0xce, 0xad, 0xe7, 0x7a, 0x8e, 0xb9, 0x34, 0x89, 0xf1, 0xae, 0xeb, 0xf4, 0x4e, 0xc8, 0x9b, 0x41,
	0xcf, 0xed, 0x9c, 0x98, 0xcb, 0x68, 0x07, 0x90, 0x44, 0x3b, 0xf6, 0xeb, 0x37, 0x5d, 0xec, 0x4c,
	0xf0, 0x15, 0xb4, 0x07, 0x77, 0x66, 0x9e, 0xd7, 0xb0, 0xdb, 0xef, 0xbd, 0x2b, 0x22, 0x99, 0xab,
	0xa8, 0x01, 0x15, 0x65, 0x81, 0xb1, 0x8b, 0xcd, 0xdf, 0x8c, 0x83, 0xef, 0x0d, 0x68, 0xcc, 0x7f,
	0x0a, 0x65, 0xa5, 0x12, 0xb9, 0x56, 0xa9, 0x84, 0x6e, 0x56, 0x3a, 0x8b, 0xce, 0x57, 0x7a, 0x0b,
	0xb6, 0xa5, 0xd2, 0x76, 0xfb, 0xcf, 0xbb, 0xf8, 0xf4, 0x7a, 0xa9, 0x73, 0x7e, 0x45, 0xa9, 0x0d,
	0xa8, 0x48, 0x78, 0x9a, 0xda, 0x8f, 0x06, 0x34, 0xe6, 0xbf, 0x97, 0xa8, 0x06, 0xeb, 0x7d, 0xb7,
	0xb0, 0x58, 0x50, 0x23, 0xd1, 0x31, 0x3d, 0x1f, 0x3b, 0x9d, 0x53, 0xd3, 0x40, 0x9b, 0xd0, 0xb4,
	0x7b, 0x5d, 0xa7, 0x2f, 0x7b, 0x3b, 0x70, 0xb1, 0xef, 0x9c, 0x98, 0x8b, 0x33, 0xe0, 0x00, 0xbb,
	0xbe, 0x6b, 0xbb, 0x3d, 0xdd, 0x58, 0xcf, 0xef, 0xf8, 0xba, 0x1c, 0xdf, 0xc1, 0xfd, 0x4e, 0xcf,
	0x5c, 0x46, 0x08, 0x1a, 0x27, 0x8e, 0xed, 0xbe, 0x23, 0xf2, 0xdd, 0xa2, 0xa9, 0x32, 0x8c, 0x76,
	0x2f, 0xc2, 0x44, 0xd2, 0xac, 0x80, 0xfc, 0xee, 0xa9, 0xe3, 0xbe, 0xf1, 0x4d, 0x7a, 0xf0, 0x12,
	0xea, 0x73, 0xd7, 0x58, 0xfa, 0xf5, 0x47, 0x49, 0x32, 0x05, 0xcd, 0x05, 0x64, 0x42, 0xed, 0x34,
	0x4e, 0x4b, 0xc4, 0x90, 0x2f, 0xb9, 0x67, 0x43, 0x7e, 0x58, 0x62, 0x8b, 0x07, 0x8f, 0x00, 0xdd,
	0x5c, 0x5a, 0x59, 0xfb, 0x09, 0x15, 0x34, 0x14, 0x2c, 0x37, 0x17, 0xd0, 0x1a, 0x2c, 0x75, 0x06,
	0x5d, 0xd3, 0xf8, 0x3d, 0x00, 0x00, 0xff, 0xff, 0xb8, 0x37, 0xaa, 0x0f, 0xd7, 0x0b, 0x00, 0x00,

}
